### ISSUE TITLE
Release 0.0.16 is missing binaries

### ISSUE THREAD

**Issue by nicholasdille** [interlynk-io/sbomgr#61]
Looks like the release action has failed to publish binaries with the release

**Comment by surendrapathak** [comment]
@nicholasdille Sorry about that! The release had a problem with CDX1.5 compatibility, and we just rolled it back. I hope it doesn't mess up your pipeline. We should be able to get back to it by mid-week.

**Comment by nicholasdille** [comment]
No worries, just making sure you are aware of the missing binaries 😊
